[project]
name = "datastructures"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"

[dependency-groups]
dev = [
    "basedpyright>=1.31.4",
    "pytest>=8.4.2",
    "ruff>=0.13.0",
]
