name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-test-lint:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python from file
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.8.17
          enable-cache: true

      - name: Install the project
        shell: bash
        run: uv sync --locked --all-extras --dev

      - name: Run basedpyright
        run: uv run basedpyright

      - name: Ruff check
        run: uv run ruff check --output-format=github

      - name: Ruff format (check only)
        run: uv run ruff format --check

      - name: Run pytest
        run: uv run pytest tests
